### ISSUE TITLE
Import failed, even on fresh Comfy installs

### ISSUE THREAD

**Issue by yotraxxx** [flowtyone/ComfyUI-Flowty-CRM#3]
Hi :)

I cannot manage to load your promising nodes, even on two different fresh comfyui installs, with only flowty-CRM and Comfy-manager in my custom nodes folder.
I pip installed both the requirments.txt files too.
I'm using Comfyui_portable

Here's what the log tells me on start-up :

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\__init__.py", line 13, in <module>
    from .crmlib.model import CRM
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\crmlib\model\__init__.py", line 1, in <module>
    from .crm.model import CRM
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\crmlib\model\crm\model.py", line 4, in <module>
    import trimesh
ModuleNotFoundError: No module named 'trimesh'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM module for custom nodes: No module named 'trimesh'

**Comment by flowtyone** [comment]
Please install the dependencies as shown in the readme

**Comment by SimRow** [comment]
Getting the same log, same problem here and the dependencies are installed like the readme instructs to.

**Comment by flowtyone** [comment]
Oh, I didn't notice you were using the portable version of comfyui. I don't really know what steps are needed to get the nodes installed in it, would be useful if someone could do some trial and error and reply if there's a successful attempt

**Comment by yotraxxx** [comment]
> > Hi :)
> > ....with only flowty-CRM and Comfy-manager in my custom nodes folder.
> 
> If you read the readme, you need [ComfyUI_essentials](https://github.com/cubiq/ComfyUI_essentials) node. Also sample workflow downloaded don't open at all, but is simple remade workflow following image. I'm on portable version and after remade workflow from scratch, i'm able to run it. Remember to download needed models and put it in correct folder, i mean if you have enable custom model folder, you need to put models here, or CUI don't see it.

I Did all of that as well before posting and also tried another install :-/

**Comment by TinyForge** [comment]
Also ran into this issue using `ComfyUI_windows_portable`, but managed to resolve it. The portable version has its own python environment embedded within it, and you need to kick off your `pip install` commands using that environment. You can do it easily by browsing to 

```
../ComfyUI_windows_portable/update/update_comfyui_and_python_dependencies.bat
```

And appending the following lines to the bottom of your script, if you've already installed the required dependencies, as listed in the readme.

```
..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements.txt"
..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements-cuda.txt"
..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI_essentials\requirements.txt"
```

Then running the above bat file should install all your dependencies.

**Comment by flowtyone** [comment]
I'll keep this issue open so people can see the solution, might also add it to the readme

**Comment by yotraxxx** [comment]
> Also ran into this issue using `ComfyUI_windows_portable`, but managed to resolve it. The portable version has its own python environment embedded within it, and you need to kick off your `pip install` commands using that environment. You can do it easily by browsing to
> 
> ```
> ../ComfyUI_windows_portable/update/update_comfyui_and_python_dependencies.bat
> ```
> 
> And appending the following lines to the bottom of your script, if you've already installed the required dependencies, as listed in the readme.
> 
> ```
> ..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements.txt"
> ..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements-cuda.txt"
> ..\python_embeded\python.exe -s -m pip install -r "..\ComfyUI\custom_nodes\ComfyUI_essentials\requirements.txt"
> ```
> 
> Then running the above bat file should install all your dependencies.

Worked perfectly ! Thank you :)
Depndencies and nodes loaded as well.

But... Now I encounter the same issue mentionned here:
https://github.com/flowtyone/ComfyUI-Flowty-CRM/issues/4

I tried to bypass it through your solution above, but no luck...
I'll also put the details in the log  in a message concerning the "nvdiffrast" issue

Thank you again, and many thanks to @flowtyone

**Comment by TinyForge** [comment]
I've made a follow-up post on #4

**Comment by Xenodimensional** [comment]
It would be nice if this wasn't like.. you know.. right at the bottom of the page! 

How do I remove all the dependencies it installed into my main system Pythion?
