### ISSUE TITLE
No module named 'nvdiffrast'

### ISSUE THREAD

**Issue by chrish-slingshot** [flowtyone/ComfyUI-Flowty-CRM#4]
I get the following error when running the provided example workflow, using CUDA:

```
Error occurred when executing CRMModelerCuda:

No module named 'nvdiffrast'

File "S:\StableDiffusion\UI\ComfyUI_2024_02_01\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\StableDiffusion\UI\ComfyUI_2024_02_01\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\StableDiffusion\UI\ComfyUI_2024_02_01\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\StableDiffusion\UI\ComfyUI_2024_02_01\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\__init__.py", line 327, in make_model
mesh = generate3d_cuda(crm_model, rgb, ccm, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "S:\StableDiffusion\UI\ComfyUI_2024_02_01\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\crmlib\inference.py", line 68, in generate3d_cuda
import nvdiffrast.torch as dr
```

**Comment by flowtyone** [comment]
Please install the dependencies as shown in the readme

**Comment by yotraxxx** [comment]
Same issue here.
I was finally able to install the nodes on ComfyUI Portable thanks to @Tinyforge (see https://github.com/flowtyone/ComfyUI-Flowty-CRM/issues/3) but now have this "nvdiffrast" error.

Tried to bypass it, but when dependencies are called (requirements-cuda.txt), the terminal displays this message:



Collecting git+https://github.com/NVlabs/nvdiffrast (from -r ..\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements-cuda.txt (line 1))
  Cloning https://github.com/NVlabs/nvdiffrast to c:\users\xxxxxxxxxxxxxx\appdata\local\temp\pip-req-build-pu0bwuyx
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast 'C:\Users\xxxxxxxxxxxxxx\AppData\Local\Temp\pip-req-build-pu0bwuyx'
  Resolved https://github.com/NVlabs/nvdiffrast to commit c5caf7bdb8a2448acc491a9faa47753972edd380
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxxxxxxxxxxxxx\AppData\Local\Temp\pip-req-build-pu0bwuyx\setup.py", line 9, in <module>
          import nvdiffrast
      ModuleNotFoundError: No module named 'nvdiffrast'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by flowtyone** [comment]
Unfortunately I'm not on windows but this reddit comment might help https://www.reddit.com/r/comfyui/s/35AxOP9nbn

**Comment by TinyForge** [comment]
I ran into this issue due to having a portable version of ComfyUI. You need to install it using the embedded python version that gets packaged within the portable ComfyUI file.

This issue is due to how the nvdiffrast project is set up and how it interacts with `pip install -r requirements.txt`. It uses method 6 at [this link](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) to manage it's version, which has the following warning:

> Although this technique is common, beware that it will fail if sample/__init__.py imports packages from install_requires dependencies, which will very likely not be installed yet when setup.py is run.

[This issue](https://github.com/NVlabs/nvdiffrast/issues/170) talks about it specifically. This is probably not the best way to work around it, but I managed to get the package installed by cloning https://github.com/NVlabs/nvdiffrast locally and editing the `setup.py` file to directly reference the version number on `line 18` and remove the `import nvdiffrast` on `line 9`. My new `setup.py` looks like this now:

```
import setuptools
import os

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="nvdiffrast",
    version='0.3.1',
    ...
```

After doing that, I ran this command in the root dir for nvdiffrast, directly referencing my embedded python environment within the portable version of ComfyUI:

```
// Your path will be different
D:\AI\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install .
```

After this, it should be correctly installed.

**Comment by yotraxxx** [comment]
:(

Same error again, despite to have followed all your crystal clear and well documented instructions several times...
I've also read on a reddit thread a "solution" implying Cuda toolkit v12.1 and Visual Studio for compiling stuffs, but it's far beyond my knowledge now...

Anyway, Thank you @TinyForge & @flowtyone  :)

**Comment by yotraxxx** [comment]
> :(
> 
> Same error again, despite to have followed all your crystal clear and well documented instructions several times... I've also read on a reddit thread a "solution" implying Cuda toolkit v12.1 and Visual Studio for compiling stuffs, but it's far beyond my knowledge now...
> 
> Anyway, Thank you @TinyForge & @flowtyone :)

Well...

Just tried a direct "pip install .", and it worked, sort of...
Obviously, it targets my python version in PYTHONPATH, so useless with the embedded python in my comfy directory.

I copied/pasted "nvdiffrast", "nvdiffrast-0.3.1.dist-info", "kiui" and "kiui-0.2.5.dist-info" directories from
C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python310\Lib\site-packages
to
E:\ComfyUI_PLAYGROUND02\python_embeded\Lib\site-packages

It kind of worked, because now I have a fresh new error (progress tho' !!) ->

"Error occurred when executing CRMModelerCuda:
DLL load failed while importing nvdiffrast_plugin: Le module spécifié est introuvable." (module not found)

**Comment by HotHams** [comment]
Thank you for all the work on the nodes and for the thread. I got as far as the nvdiffrast issue, as I use the Windows portable version of ComfyUI. I'm not sure opting for regular ComfyUI is an option just yet on my end, so I'm curious whether this is something that can be easily overcome or might be looked into in the near future for portable users?

**Comment by ghostsquad** [comment]
> I ran into this issue due to having a portable version of ComfyUI. You need to install it using the embedded python version that gets packaged within the portable ComfyUI file.
> 
> This issue is due to how the nvdiffrast project is set up and how it interacts with `pip install -r requirements.txt`. It uses method 6 at [this link](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) to manage it's version, which has the following warning:
> 
> > Although this technique is common, beware that it will fail if sample/**init**.py imports packages from install_requires dependencies, which will very likely not be installed yet when setup.py is run.
> 
> [This issue](https://github.com/NVlabs/nvdiffrast/issues/170) talks about it specifically. This is probably not the best way to work around it, but I managed to get the package installed by cloning https://github.com/NVlabs/nvdiffrast locally and editing the `setup.py` file to directly reference the version number on `line 18` and remove the `import nvdiffrast` on `line 9`. My new `setup.py` looks like this now:
> 
> ```
> import setuptools
> import os
> 
> with open("README.md", "r") as fh:
>     long_description = fh.read()
> 
> setuptools.setup(
>     name="nvdiffrast",
>     version='0.3.1',
>     ...
> ```
> 
> After doing that, I ran this command in the root dir for nvdiffrast, directly referencing my embedded python environment within the portable version of ComfyUI:
> 
> ```
> // Your path will be different
> D:\AI\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install .
> ```
> 
> After this, it should be correctly installed.

I can confirm these steps work.

My paths: `g/ComfyUI_windows_portable`

from `/g` I ran `git clone https://github.com/NVlabs/nvdiffrast`

edited `setup.py` as stated above. Note, as of this writing, the current tag is `0.3.1`, so that's the version to use. You can find the latest tags here: https://github.com/NVlabs/nvdiffrast/tags

followed by `ComfyUI_windows_portable/python_embeded/python.exe -s -m pip install nvdiffrast/`

**Comment by yotraxxx** [comment]
> > I ran into this issue due to having a portable version of ComfyUI. You need to install it using the embedded python version that gets packaged within the portable ComfyUI file.
> > This issue is due to how the nvdiffrast project is set up and how it interacts with `pip install -r requirements.txt`. It uses method 6 at [this link](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) to manage it's version, which has the following warning:
> > > Although this technique is common, beware that it will fail if sample/**init**.py imports packages from install_requires dependencies, which will very likely not be installed yet when setup.py is run.
> > 
> > 
> > [This issue](https://github.com/NVlabs/nvdiffrast/issues/170) talks about it specifically. This is probably not the best way to work around it, but I managed to get the package installed by cloning https://github.com/NVlabs/nvdiffrast locally and editing the `setup.py` file to directly reference the version number on `line 18` and remove the `import nvdiffrast` on `line 9`. My new `setup.py` looks like this now:
> > ```
> > import setuptools
> > import os
> > 
> > with open("README.md", "r") as fh:
> >     long_description = fh.read()
> > 
> > setuptools.setup(
> >     name="nvdiffrast",
> >     version='0.3.1',
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After doing that, I ran this command in the root dir for nvdiffrast, directly referencing my embedded python environment within the portable version of ComfyUI:
> > ```
> > // Your path will be different
> > D:\AI\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this, it should be correctly installed.
> 
> I can confirm these steps work.
> 
> My paths: `g/ComfyUI_windows_portable`
> 
> from `/g` I ran `git clone https://github.com/NVlabs/nvdiffrast`
> 
> edited `setup.py` as stated above. Note, as of this writing, the current tag is `0.3.1`, so that's the version to use. You can find the latest tags here: https://github.com/NVlabs/nvdiffrast/tags
> 
> followed by `ComfyUI_windows_portable/python_embeded/python.exe -s -m pip install nvdiffrast/`

Confirmed !! This worked ! :) Thank you all !

**Comment by LPSCRYPT** [comment]
I'm running on Ubuntu and still getting this error: any tips?

**Comment by Publicoprivado** [comment]
I've followed instructions to the T and went through installing Nvdiffrast but now I'm confronted by "Kiui" not installed, got around installing it and now it says "Error occurred when executing CRMModelerCuda: Ninja is required to load C++ extensions" but ninja is already installed.

I am running ComfyUI Portable, Win10, Cuda 12.1, I installed all the dependencies as the Git indicated and followed this instructions to modify setup to install Nvdiffrast flawlesly, what am I missing?. My only difference is I have Torch 2.2.2+cu121

**Comment by se7enth** [comment]
> I ran into this issue due to having a portable version of ComfyUI. You need to install it using the embedded python version that gets packaged within the portable ComfyUI file.
> 
> This issue is due to how the nvdiffrast project is set up and how it interacts with `pip install -r requirements.txt`. It uses method 6 at [this link](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) to manage it's version, which has the following warning:
> 
> > Although this technique is common, beware that it will fail if sample/**init**.py imports packages from install_requires dependencies, which will very likely not be installed yet when setup.py is run.
> 
> [This issue](https://github.com/NVlabs/nvdiffrast/issues/170) talks about it specifically. This is probably not the best way to work around it, but I managed to get the package installed by cloning https://github.com/NVlabs/nvdiffrast locally and editing the `setup.py` file to directly reference the version number on `line 18` and remove the `import nvdiffrast` on `line 9`. My new `setup.py` looks like this now:
> 
> ```
> import setuptools
> import os
> 
> with open("README.md", "r") as fh:
>     long_description = fh.read()
> 
> setuptools.setup(
>     name="nvdiffrast",
>     version='0.3.1',
>     ...
> ```
> 
> After doing that, I ran this command in the root dir for nvdiffrast, directly referencing my embedded python environment within the portable version of ComfyUI:
> 
> ```
> // Your path will be different
> D:\AI\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install .
> ```
> 
> After this, it should be correctly installed.

I followed ，but still wrong... here is my log, somebody could help to deal with the problem?
 error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\setuptools\__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Scripts\python310.zip\distutils\core.pyc
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by EIegance** [comment]
For anyone coming across this looking for a fix; the only thing that solved it for me after **many** hours was:

- Switching off of ComfyUI portable version (Probably isn't necessary as long as you make sure you're not running cu118, just something I did)
- Uninstalling Torch, and everything related to cu118
- [Installing PyTorch cu112 ](https://pytorch.org/get-started/locally/)_specifically the nightly version_ 
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`
- Then reinstalling Flowty-CRM + all of its requirements
- Updating to Python version: 3.12.1

The issue seems to be cu118
I basically reinstalled everything and then made sure ComfyUI was running PyTorch 2.4.0+cu121. I doubt you'll have to reinstall everything as long as you fully switch your PyTorch version. But in case you still can't get it working I'd recommend starting fresh, and its easy if you still have your _ComfyUI_windows_portable_ to import everything from. Also I doubt changing my python version did anything but I'm just mentioning it in case it did help.

**Comment by gerroon** [comment]
Hi

I am using nightly Comfy and I cant get this working :( I tried the suggested editing of the setup.py with no luck/

Here I am trying to install with the requirements.txt

```
c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM>c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe -m pip install -r requirements-cuda.txt
Collecting git+https://github.com/NVlabs/nvdiffrast (from -r requirements-cuda.txt (line 1))
  Cloning https://github.com/NVlabs/nvdiffrast to c:\users\USER\appdata\local\temp\pip-req-build-s77tpywi
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast 'C:\Users\USER\AppData\Local\Temp\pip-req-build-s77tpywi'
  Resolved https://github.com/NVlabs/nvdiffrast to commit c5caf7bdb8a2448acc491a9faa47753972edd380
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USER\AppData\Local\Temp\pip-req-build-s77tpywi\setup.py", line 9, in <module>
          import nvdiffrast
      ModuleNotFoundError: No module named 'nvdiffrast'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by makemorereliablesoftware** [comment]
same issue here, exhausted all solutions provided for this problem and then tried some more. Even the obvious solutions provided by flowtyone, i wonder if they really think we didn't install the decencies.

**Comment by 3blackbar** [comment]
Hey dev! Update your dependencies properly, you have to install https://github.com/NVlabs/nvdiffrast
Most people are not devs and coders, when you halfass it like this, youll get ppl complaining and nothing else.
