### ISSUE TITLE
requirements-cuda.txt installation problem

### ISSUE THREAD

**Issue by Ratinod** [flowtyone/ComfyUI-Flowty-CRM#7]
I successfully (without any errors in the console during installation) installed the dependencies using the command:
`python_embeded\python.exe -s -m pip install -r ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements.txt`

However, trying to install requirements-cuda.txt using:
`python_embeded\python.exe -s -m pip install -r ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements-cuda.txt`
gives this error:
```
Collecting git+https://github.com/NVlabs/nvdiffrast (from -r ComfyUI\custom_nodes\ComfyUI-Flowty-CRM\requirements-cuda.txt (line 1))
  Cloning https://github.com/NVlabs/nvdiffrast to c:\users\username\appdata\local\temp\pip-req-build-rio45x6g
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast 'C:\Users\username\AppData\Local\Temp\pip-req-build-rio45x6g'
  Resolved https://github.com/NVlabs/nvdiffrast to commit c5caf7bdb8a2448acc491a9faa47753972edd380
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-req-build-rio45x6g\setup.py", line 9, in <module>
          import nvdiffrast
      ModuleNotFoundError: No module named 'nvdiffrast'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
How to fix this?

**Comment by Ratinod** [comment]
It doesn't matter. If you have 8GB VRAM you don't even have to try. CRM Pose Sampler ->out of memory...
